export const Projects = [
  {
    _id: 1,
    title: "MovieBuzz",
    slug: "moviebuzz",
    date: "Oct - Nov 2023",
    description:
      "Developed MovieBuzz, a movie streaming platform using the MERN stack with features like genre-based filtering, dynamic search, movie playback, and subscription purchasing with Braintree. Built a secure backend and integrated Firebase for storing images and videos.",
    skills: "React, Node, mongodb, Firebase, Payment Integreation",
    image: "/images/project4/Landingpage.png",
    link: "https://moviebuzz-jade-one.vercel.app/register",
    gitRipo: "https://github.com/pintuSINGH2000/MovieBuzz",
    video: "https://youtu.be/tE31KSp-hQA",
  },
  {
    _id: 2,
    title: "ChitChat",
    slug: "chitchat",
    date: "Oct - Nov 2023",
    description:
      "Developed a feature-rich chatting application using Next.js and React, integrating ZegoCloud for video and audio calling. Implemented live chat with features like sending audio, documents, emojis, and more, along with secure Google login functionality for seamless user access.",
    skills: "React, Nextjs, mongodb, zegoClud",
    image: "/images/chitchat.png",
    link: "https://github.com/pintuSINGH2000/chitchat-frontend",
    gitRipo: "https://github.com/pintuSINGH2000/chitchat-backend",
    video: "https://youtu.be/6vZP8WTlVVk",
  },
  {
    _id: 3,
    title: "Formbot",
    slug: "formbot",
    date: "July - Aug 2024",
    description:
      "Developed FormBot, an AI-driven platform for creating and sharing chat-based forms with real-time data storage.Features like form creation, customizable themes, folder organization, and secure user access. Enabled admins to analyze form responses and manage data efficiently",
    skills: "React, Node, mongodb, mongoose",
    image: "/images/formbot.png",
    link: "https://formbot-gray.vercel.app/",
    gitRipo: "https://github.com/pintuSINGH2000/formbot",
    video: "https://youtu.be/HfqFrrH88fo",
  },
  {
    _id: 4,
    title: "Quizzie",
    slug: "quizzie",
    date: "June - July 2024",
    description:
      "Developed Quizzi, an app for creating, sharing, and analyzing quizzes and polls, with features like timers, quiz analytics, and poll insights.Allowing secure access for admins while restricting unauthorized users to only participate in quizzes and polls.",
      skills: "React, Node, mongodb, Github",
    image: "/images/quiz.png",
    link: "https://quiz-app-frontend-xi.vercel.app/",
    gitRipo: "https://github.com/pintuSINGH2000/QuizApp-frontend",
    video: "https://youtu.be/V1c8vJBwTPc",
  },
  {
    _id: 5,
    title: "Task Manager",
    slug: "task-manager",
    date: "May - June 2024",
    description:"Developed TaskManager, an app for creating, assigning, and tracking tasks with features like progress dashboards, task filtering, and analytics on completion rates and priorities.It includes secure user management and restricts unauthorized users to read-only task views.",
    skills: "React, Node, mongodb, Postman, Render",
    image: "/images/task.png",
    link: "https://quiz-app-frontend-xi.vercel.app/",
    gitRipo: "https://github.com/pintuSINGH2000/QuizApp-frontend",
    video: "https://youtu.be/yjGS-H3uQCs",
  },
  {
    _id: 6,
    title: "Ecommerce",
    slug: "ecommerce",
    date: "July - Aug 2023",
    description:
      "Developed a feature-rich E-commerce application with dynamic product selection, authentication, shopping cart, and checkout functionality. Built REST APIs following best practices and utilized MongoDB for efficient data storage, ensuring seamless backend integration and user experience.",
    skills: "React, Node, mongodb, Payment Integreation",
    image: "/images/project1/landingpage.png",
    link: "https://ecommerce.cyclic.cloud/",
    gitRipo: "https://github.com/pintuSINGH2000/Ecommerce",
    video: "https://youtu.be/HfqFrrH88fo",
  },
  {
    _id: 7,
    title: "Pocket Note",
    slug: "note",
    date: "April - May 2024",
    description:"Developed Pocket Note, an app for creating note groups, writing and organizing notes by date and time, and sharing them effortlessly. It enables seamless note management and collaboration.",
    link:"https://pocket-notes-amber-two.vercel.app/",
    image:"/images/project6/message.png", 
    skills: "React, localhost",
    gitRipo: "https://github.com/pintuSINGH2000/Pocket-Notes",
    video: "https://youtu.be/0yyx7ZiqD7k"
  },
  {
    _id: 8,
    title: "Super App",
    slug: "superapp",
    date: "April - May 2024",
    description:"Developed Super App, transforming intricate Figma designs into a fully functional application with pixel-perfect precision. Focused on delivering a seamless user experience through clean, responsive, and visually appealing interfaces.",
    link:"https://super-app-ebon.vercel.app/",
    image:"/images/super.png", 
    skills: "React, localhost",
    gitRipo: "https://github.com/pintuSINGH2000/SuperApp",
    video: "https://youtu.be/g9E0Mh6Tz0M"
  },
];

