export const Skill = [
    {
        _id:1,
        name:"C++",
        path:"/images/cplus.png"
    },
    {
        _id:2,
        name:"HTML",
        path:"/images/html.png"
    },
    {
        _id:3,
        name:"CSS",
        path:"/images/css.png"
    },
    {
        _id:4,
        name:"JavaScript",
        path:"/images/javascript.png"
    },
    {
        _id:5,
        name:"React",
        path:"/images/react.png"
    },
    {
        _id:6,
        name:"Node JS",
        path:"/images/node.png"
    },
    {
        _id:7,
        name:"Express JS",
        path:"/images/express.png"
    },
    {
        _id:8,
        name:"Mongo DB",
        path:"/images/mongo.png"
    },
    {
        _id:9,
        name:"Mongoose",
        path:"/images/mongoose.png"
    },
    {
        _id:10,
        name:"Bootstrap",
        path:"/images/bootstrap.png"
    },
    {
        _id:11,
        name:"Redux",
        path:"/images/redux.png"
    },
    {
        _id:12,
        name:"Git",
        path:"/images/git.png"
    },
    {
        _id:13,
        name:"Nextjs",
        path:"/images/nextjs.png"
    },
    {
        _id:14,
        name:"Rest",
        path:"/images/rest.png"
    },
    {
        _id:15,
        name:"Linux",
        path:"/images/linux.png"
    },
    {
        _id:16,
        name:"Https",
        path:"/images/https.png"
    },
]